/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnotherPageRouteImport } from './routes/anotherPage'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiClaudeChatRouteImport } from './routes/api/claude-chat'
import { Route as ApiV1CorsProxySplatRouteImport } from './routes/api/v1/cors/proxy/$'

const AnotherPageRoute = AnotherPageRouteImport.update({
  id: '/anotherPage',
  path: '/anotherPage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClaudeChatRoute = ApiClaudeChatRouteImport.update({
  id: '/api/claude-chat',
  path: '/api/claude-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CorsProxySplatRoute = ApiV1CorsProxySplatRouteImport.update({
  id: '/api/v1/cors/proxy/$',
  path: '/api/v1/cors/proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/api/claude-chat': typeof ApiClaudeChatRoute
  '/api/v1/cors/proxy/$': typeof ApiV1CorsProxySplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/api/claude-chat': typeof ApiClaudeChatRoute
  '/api/v1/cors/proxy/$': typeof ApiV1CorsProxySplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/api/claude-chat': typeof ApiClaudeChatRoute
  '/api/v1/cors/proxy/$': typeof ApiV1CorsProxySplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/anotherPage' | '/api/claude-chat' | '/api/v1/cors/proxy/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anotherPage' | '/api/claude-chat' | '/api/v1/cors/proxy/$'
  id:
    | '__root__'
    | '/'
    | '/anotherPage'
    | '/api/claude-chat'
    | '/api/v1/cors/proxy/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnotherPageRoute: typeof AnotherPageRoute
  ApiClaudeChatRoute: typeof ApiClaudeChatRoute
  ApiV1CorsProxySplatRoute: typeof ApiV1CorsProxySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/anotherPage': {
      id: '/anotherPage'
      path: '/anotherPage'
      fullPath: '/anotherPage'
      preLoaderRoute: typeof AnotherPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/claude-chat': {
      id: '/api/claude-chat'
      path: '/api/claude-chat'
      fullPath: '/api/claude-chat'
      preLoaderRoute: typeof ApiClaudeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/cors/proxy/$': {
      id: '/api/v1/cors/proxy/$'
      path: '/api/v1/cors/proxy/$'
      fullPath: '/api/v1/cors/proxy/$'
      preLoaderRoute: typeof ApiV1CorsProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnotherPageRoute: AnotherPageRoute,
  ApiClaudeChatRoute: ApiClaudeChatRoute,
  ApiV1CorsProxySplatRoute: ApiV1CorsProxySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
